spring:
  application:
    name: tlias-web-management
  #配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

#Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关
    #识别数据库传递的字段，为实体类成功赋值
    map-underscore-to-camel-case: true
  #配置图片保存参数
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 100MB

    #配置事务管理日志级别
    logging:
      level:
        org.springframework.jdbc.support.JdbcTransactionManager: debug